// <auto-generated />
namespace HL_V1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class articke : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(articke));
        
        string IMigrationMetadata.Id
        {
            get { return "201809290642351_articke"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
